### PR TITLE
refactored navigation and created global state with context api

### PR DESCRIPTION
**Pull request by aayam-shrestha**
1. All the stack and tab navigator code is in a folder called 'navigation'.
2. I created a 'util' folder that contains code for global state management using the context API. So the username will now be made global after entering it into the login page. It can be accessed from any screen in the app now.

### CODE REVIEW

**Comment by aayam-shrestha** [comment]
The header bar doesn't have the about icon right now. I changed the nested stacks so it got changed. I didn't bother to mess around with the header since we still need to decide what to do with the menu and the help.

**Comment by aayam-shrestha** [comment]
To use the global state for user in any screen:
1. import { useContext } from 'react';
2. import { UserContext } '../util/UserManager';

In the export default function, do this:
const { user } = useContext(UserContext);

You should be able to access the username by typing {user} anywhere in the function now.

**Comment by aayam-shrestha** [comment]
I also added pull from top to refresh when you're at the top of the post page.

**Comment by anjanasainju** [comment]
Looks great! This will solve a lot of our problems!

**Pull request merged**
